{
 "title": "PoC Dashboard",
 "description": "This is a proof of concept dashboard",
 "time": { "from": "now-6M", "to": "now" },
 "panels": [
  {
   "title": "Template Adoption Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "openhexa_kpis",
     "rawSql": "SELECT adoption_rate FROM public.kpi_adoption_rate;"
    }
   ]
  },
  {
   "title": "Active Pipeline Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "openhexa_kpis",
     "rawSql": "SELECT active_rate FROM kpi_active_pipeline_rate;"
    }
   ]
  },
  {
   "title": "First 3 Runs Failure Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "openhexa_kpis",
     "rawSql": "SELECT AVG(failure_rate) FROM kpi_first_3_failures;"
    }
   ]
  },
  {
   "title": "Average Runs per Day",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "openhexa_kpis",
     "rawSql": "SELECT AVG(runs_per_day) FROM kpi_run_frequency;"
    }
   ]
  },
  {
   "title": "Last Run Status",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "openhexa_kpis",
     "rawSql": "SELECT status, COUNT(*)\nFROM kpi_last_run_status\nGROUP BY status;"
    }
   ]
  },
  {
   "title": "Pipeline Creation Trend",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 7, "y": 4 },
   "targets": [
    {
     "dataset": "openhexa_kpis",
     "rawSql": "SELECT\n    date,\n    template_pipelines,\n    total_pipelines\nFROM kpi_pipeline_trend;"
    }
   ]
  },
  {
   "title": "Total vs Template Pipelines",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "openhexa_kpis",
     "rawSql": "SELECT\n    COUNT(*) AS total_pipelines,\n    COUNT(*) FILTER (WHERE template_id IS NOT NULL) AS template_pipelines\nFROM pipelines;"
    }
   ]
  },
  {
   "title": "Template Usage",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 15, "x": 7, "y": 11 },
   "targets": [
    {
     "dataset": "openhexa_kpis",
     "rawSql": "SELECT\n    template_id,\n    pipeline_count\nFROM kpi_template_usage\nORDER BY pipeline_count DESC;"
    }
   ]
  }
 ]
}